project:
  type: website
  output-dir: docs

website:
  title: "Neha Dixit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - dataviz.qmd
        text: Data Viz

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page_layout: full



